# Variables globales por defecto para nuestro microservicio
replicaCount: 1

image:
  repository: mi-inventario
  tag: "v1"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

# Esto servirá más adelante para simular entornos
environment: "development"